Fix label display in modals
moreonion/ae_admin pull request #5
Opened 2018-04-09 11:52 UTC by katzmo

When clicking "edit" on a media image upload field, some labels and toggles in the modal look really weird or even unusable. This is due to some styles in ctools/css/modal.css that obviously don’t work well in combination with ae_admin. By adding a copy of ctools’ modal.css, we’re able to override it and fix the issue.

2018-05-17 10:38 UTC, alex-mo requested changes
* the commented out code can be deleted (why keeping around dead code?)
* the images are missing

2018-05-17 10:54 UTC, alex-mo commented
besides the requested changes: the labels do look correct afterwards, so: :+1:

2018-05-17 14:01 UTC, katzmo commented
We should test if we actually need any of those styles…

2018-10-15 14:29 UTC, torotil commented
So this is not ready to be merged yet, right? How should we proceed with it?

2018-12-17 19:28 UTC, torotil commented
This seems to have lost traction.

2018-12-17 19:28 UTC, closed without merging